const ALERT = 'ALERT';
const REFETCH_CHAT = 'REFETCH';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE';
const NEW_ATTACHMENT = 'NEW_ATTACH'
const NEW_REQUEST = 'NEW_REQUEST';

export {
    ALERT,
    REFETCH_CHAT,
    NEW_MESSAGE_ALERT,
    NEW_ATTACHMENT,
    NEW_REQUEST,
}